revert testing changes in msal submodule check and update wpj openssl submodule checkout

diff --git a/azure_pipelines/msal_submodule_check.yaml b/azure_pipelines/msal_submodule_check.yaml
--- a/azure_pipelines/msal_submodule_check.yaml
+++ b/azure_pipelines/msal_submodule_check.yaml
@@ -1,145 +1,62 @@
-# Xcode
-# Build, test, and archive an Xcode workspace on macOS.
-# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
-# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode
-
-trigger:
-  branches:
-    include:
-    - dev
-
+# Pipeline will be triggered for PR & any updates on the PR on all branches
 pr:
-  autoCancel: true
   branches:
     include:
     - '*'
-  drafts: true
 
-pool:
-  name: 'Azure Pipelines'
+# Trigger CI for only main/release branches
+trigger:
+  branches:
+    include:
+    - main
+    - release/*
 
 resources:
  repositories:
-   - repository: azure-activedirectory-tokenbroker-for-objc
+   - repository: microsoft-authentication-library-for-objc
      type: github
      endpoint: 'MSAL ObjC Service Connection'
-     name: AzureAD/azure-activedirectory-tokenbroker-for-objc
+     name: AzureAD/microsoft-authentication-library-for-objc
 
-   - repository: WorkplaceJoin-for-iOS
-     type: github
-     endpoint: 'MSAL ObjC Service Connection'
-     name: AzureAD/WorkplaceJoin-for-iOS
-
+# Define parallel jobs that run build script for specified targets
 jobs:
 - job: 'Validate_Pull_Request'
+  strategy:
+    maxParallel: 3
+    matrix:
+      IOS_FRAMEWORK:
+        target: "iosFramework iosTestApp sampleIosApp sampleIosAppSwift"
+      MAC_FRAMEWORK:
+        target: "macFramework"
+      VISION_FRAMEWORK:
+        target: "visionOSFramework"
   displayName: Validate Pull Request
   pool:
     vmImage: 'macOS-14'
     timeOutInMinutes: 30
 
   steps:
-  - checkout: azure-activedirectory-tokenbroker-for-objc
-    displayName: 'Checkout Broker'
-    clean: false
-    submodules: false
-    fetchTags: true
-    persistCredentials: true
-
-  - task: Bash@3
-    displayName: 'Checkout MSAL, ADAL, and submodules'
+  - script: |
+          /bin/bash -c "sudo xcode-select -s /Applications/Xcode_15.4.app"
+    displayName: 'Switch to use Xcode 15.4'
+  - task: CmdLine@2
+    displayName: Uninstalling xcpretty v0.4.0
     inputs:
-      workingDirectory: $(Pipeline.Workspace)/s
-      targetType: 'inline'
       script: |
-        cd azure-activedirectory-tokenbroker-for-objc
-        git submodule update --init --recursive ADAuthenticationBroker/Frameworks/adal
-        git submodule update --init ADAuthenticationBroker/Frameworks/microsoft-authentication-library-for-objc
-
-  - checkout: self
-    displayName: 'Checkout IdentityCore'
-    clean: false
-    submodules: false
-    fetchTags: true
-    path: 's/azure-activedirectory-tokenbroker-for-objc/ADAuthenticationBroker/Frameworks/microsoft-authentication-library-for-objc/MSAL/IdentityCore'
-    persistCredentials: true
-
-  - checkout: WorkplaceJoin-for-iOS
-    displayName: 'Checkout WPJ'
-    clean: false
-    submodules: false
-    fetchTags: true
-    path: 's/azure-activedirectory-tokenbroker-for-objc/ADAuthenticationBroker/Frameworks/WorkplaceJoin-for-iOS'
-    persistCredentials: true
-
-  - task: AzureCLI@2
+        gem uninstall xcpretty -I --version 0.4.0
+      failOnStderr: false
+  - task: CmdLine@2
+    displayName: Installing xcpretty v0.3.0
     inputs:
-      azureSubscription: 'AuthSdkResourceManager'
-      scriptType: 'pscore'
-      scriptLocation: 'inlineScript'
-      inlineScript: |
-        # if this fails, check out this bash script that includes diagnostics:
-        # https://gist.github.com/johnterickson/19f80a3e969e39f1000d118739176e62
-        # uncomment these for more debugging spew
-        # GIT_TRACE=1
-        # GIT_CURL_VERBOSE=1
-        
-        # Note that the resoruce is specified to limit the token to Azure DevOps
-        $token = az account get-access-token --query accessToken --resource 499b84ac-1321-427f-aa17-267ca6975798 -o tsv
-        Write-Host "##vso[task.setvariable variable=aadToken;issecret=true]$token"
-  - task: Bash@3
-    displayName: 'Checkout NGC Submodules'
-    env:
-      AccessToken: $(MSAzureToken_encoded)
-    inputs:
-      workingDirectory: $(Pipeline.Workspace)/s
-      targetType: 'inline'
       script: |
-        cd azure-activedirectory-tokenbroker-for-objc/ADAuthenticationBroker/Frameworks
-        git -c http.https://msazure.visualstudio.com/DefaultCollection/One/_git/AD-MFA-NGCAuthentication.extraheader="AUTHORIZATION: bearer $(aadToken)" submodule update --init AD-MFA-NGCAuthentication
-        cd AD-MFA-NGCAuthentication
-        git -c http.https://msazure.visualstudio.com/DefaultCollection/One/_git/AD-MFA-NGCKeyProvider-ios.extraheader="AUTHORIZATION: bearer $(aadToken)" submodule update --init NGCKeyProvider
-        git -c http.https://msazure.visualstudio.com/DefaultCollection/One/_git/AD-MFA-MSAuthNetworking.extraheader="AUTHORIZATION: bearer $(aadToken)" submodule update --init MSAuthNetworking
-
-  - task: Bash@3
-    displayName: 'Checkout WPJ openssl-msft submodule'
+        gem install xcpretty -N -v 0.3.0
+      failOnStderr: true
+  - task: CmdLine@2
+    displayName: Installing dependencies
     inputs:
-      workingDirectory: $(Pipeline.Workspace)/s
-      targetType: 'inline'
       script: |
-        cd azure-activedirectory-tokenbroker-for-objc
-        REV=$(git rev-parse HEAD:ADAuthenticationBroker/Frameworks/WorkplaceJoin-for-iOS)
-        cd ADAuthenticationBroker/Frameworks/WorkplaceJoin-for-iOS
-        git pull origin $REV
-        cd Frameworks
-        git -c http.https://msazure.visualstudio.com/DefaultCollection/PlatformCrypto/_git/openssl-msft.extraheader="AUTHORIZATION: bearer $(aadToken)" submodule update --init openssl-msft
-
-  - task: Bash@3
-    displayName: 'Update WPJ submodules'
-    inputs:
-      workingDirectory: $(Pipeline.Workspace)/s
-      targetType: 'inline'
-      script: |
-        cd azure-activedirectory-tokenbroker-for-objc
-        cd ADAuthenticationBroker/Frameworks/WorkplaceJoin-for-iOS
-        git submodule update --init --recursive
-        
-  - script: 'gem uninstall xcpretty -I --version 0.4.0'
-    displayName: 'Uninstall xcpretty v0.4.0'
-
-  - script: 'gem install xcpretty -N -v 0.3.0'
-    displayName: 'Install xcpretty v0.3.0'
-    
-  - script: 'gem install slather -N'
-    displayName: 'Install slather'
-
-  - task: UsePythonVersion@0
-    displayName: 'Use Python 3.x'
-
-  - task: Bash@3
-    displayName: 'Select Xcode version'
-    inputs:
-      targetType: 'inline'
-      script: '/bin/bash -c "sudo xcode-select -s /Applications/Xcode_15.4.app"'
+        gem install slather bundler -N
+      failOnStderr: true
 
 # The following is needed to install the visionOS SDK on macos-14 vm image which
 # doesn't have visionOS installed by default.
@@ -149,21 +66,60 @@ jobs:
     inputs:
       targetType: 'inline'
       script: |
-        echo "Downloading simulator for visionOS"
-        sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
-        defaults write com.apple.dt.Xcode AllowUnsupportedVisionOSHost -bool YES
-        defaults write com.apple.CoreSimulator AllowUnsupportedVisionOSHost -bool YES
-        xcodebuild -downloadPlatform visionOS
+        echo $(target)
+        if [ $(target) == 'visionOSFramework' ]; then
+            echo "Downloading simulator for visionOS"
+            sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
+            defaults write com.apple.dt.Xcode AllowUnsupportedVisionOSHost -bool YES
+            defaults write com.apple.CoreSimulator AllowUnsupportedVisionOSHost -bool YES
+            xcodebuild -downloadPlatform visionOS
+        else
+            echo "Not visionOS job, no download needed"
+        fi
       failOnStderr: false
 
+  - checkout: microsoft-authentication-library-for-objc
+    displayName: 'Checkout MSAL'
+    clean: true
+    submodules: true
+    fetchTags: true
+    persistCredentials: true
+
+  - checkout: self
+    clean: true
+    submodules: false
+    fetchDepth: 1
+    path: 's/microsoft-authentication-library-for-objc/MSAL/IdentityCore'
+    persistCredentials: false
 
   - task: Bash@3
-    displayName: 'Run a python script for Broker'
+    displayName: Run Build script & check for Errors
     inputs:
       targetType: 'inline'
       script: |
-        cd azure-activedirectory-tokenbroker-for-objc
-        echo "executing build:./build.py"
-        python3 ./build.py
+        cd $(Agent.BuildDirectory)/s/microsoft-authentication-library-for-objc
+        { output=$(./build.py --target $(target) 2>&1 1>&3-) ;} 3>&1
+        final_status=$(<./build/status.txt)
+        echo "FINAL STATUS  = ${final_status}"
+        echo "POSSIBLE ERRORS: ${output}"
         
-
+        if [ $final_status != "0" ]; then
+          echo "Build & Testing Failed! \n ${output}" >&2
+        fi
+      failOnStderr: true
+  - task: Bash@3
+    condition: always()
+    displayName: Cleanup
+    inputs:
+      targetType: 'inline'
+      script: |
+        rm -rf $(Agent.BuildDirectory)/s/build/status.txt
+        
+  - task: PublishTestResults@2
+    condition: always()
+    displayName: Publish Test Report
+    inputs:
+      testResultsFormat: 'JUnit'
+      testResultsFiles: '$(Agent.BuildDirectory)/s/build/reports/*'
+      failTaskOnFailedTests: true
+      testRunTitle: 'Test Run - $(target)'
